### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by PendragonUK** [sargolin/ISRT-Insurgency-Sandstorm-RCON-Query-Tool#5]
Error dialog:
Something went wrong
Timed out
Wrong IP or Port?

This appears 3-4 seconds after clicking on "Get Server Info" or attempting to login to the server.

No server information is showing but if I change the map in the tool, checking the server in-game the map has changed.

Screenshots
https://imgur.com/gallery/IB5dXmY

 - OS: Windows 10
 - Version 2004

I can connect to the example server and it works as expected.

**Comment by sargolin** [comment]
Hey there, thanks for reporting that error. There is a thing wrong with your server or the data you have. Either your query port and RCON port are the same (which will not work out in the end, or your information is incorrect (sorry, to say so). When I lookup your server it has the following infos, which means, you chose the wrong query port - it should be 27131. Usually RCOn Port is somethign else, or should be. Please check that, if it's the same, you should use another port for RCON, so you don't get difficulties, when someone else like battlemetrics is polling your server and at the same time, you want to run an rcon command or you want to query the server.

Address
194.147.120.115:27102 (Game Port)
194.147.120.115:27131 (Query Port)

![image](https://user-images.githubusercontent.com/70414281/98607996-95738680-22ea-11eb-8ba2-a29d26ecb1c0.png)

I chose the right server query port, the connection works, but I got a Mutator_s error telling me, but I immediately found the bug (had a "yes" in the code where "true" should be written) and fixed that. I'll post a hotfix tomorrow morning that eliminates the error.

After I fixed this, it all runs perfectly well:

![image](https://user-images.githubusercontent.com/70414281/98608663-fbacd900-22eb-11eb-9607-968162eea060.png)


Thanks and have a good day!
Madman

**Comment by PendragonUK** [comment]
Thanks for the response I look forward to the updated tool.

**Comment by sargolin** [comment]
Hotfix released - download v0.5.1 - you can just drop the db directory on the new one and all works fine.
